config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :product_recommendations
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :product_recommendations, inverse_of: :product

end

app/models/spree/product_recommendation.rb
class Spree::ProductRecommendation < ActiveRecord::Base
  belongs_to :product, class_name: "Spree::Product"
  validates :product, presence: true
  validates :recommendation_source, presence: true

  def display_scoring_type
    Spree.t("product_recommendation.scoring_types.#{self.scoring_type}") unless self.scoring_type.blank?
  end

end

app/controllers/spree/admin/product_recommendations_controller.rb
class Spree::Admin::ProductRecommendationsController < Spree::Admin::ResourceController
  helper 'spree/product_recommendation'
  belongs_to 'spree/product', model_class: Spree::Product, find_by: :slug

  private
  def permitted_resource_params
    params.permit(product_recommendation: [:recommendation_source, :comment_title, :comment, :scoring_type, :scoring_value])[:product_recommendation]
  end

end

app/helpers/spree/product_recommendation_helper.rb
module Spree::ProductRecommendationHelper

  def scoring_types_list
    SolidusProductRecommendations.config[:scoring_types].map{|scoring_type| [Spree.t("product_recommendation.scoring_types.#{scoring_type}"), scoring_type]}
  end

end

app/views/spree/admin/product_recommendations/_form.html.erb
<%= form_for product_recommendation, url: (product_recommendation.new_record? ? admin_product_product_recommendations_path(product) : admin_product_product_recommendation_path(product, product_recommendation)) do |f| %>
  <div data-hook="admin_product_recommendation_form" class="row">
    <div class="left eight columns alpha" data-hook="admin_product_recommendation_form_left">
      <div data-hook="admin_product_recommendation_form_recommendation_source">
        <%= f.field_container :recommendation_source do %>
          <%= f.label :recommendation_source, class: 'required' %>
          <%= f.text_field :recommendation_source, :class => 'fullwidth title', :required => true %>
          <%= f.error_message_on :recommendation_source %>
        <% end %>
      </div>

      <div data-hook="admin_product_recommendation_form_scoring_type" class="alpha omega eight columns">
        <%= f.field_container :scoring_type do %>
          <%= f.label :scoring_type %>

          <%= f.select(:scoring_type, scoring_types_list) %>
          <%= f.error_message_on :scoring_type %>
        <% end %>
      </div>

      <div data-hook="admin_product_recommendation_form_scoring_value" class="alpha eight columns">
        <%= f.field_container :scoring_value do %>
          <%= f.label :scoring_value %>
          <%= f.text_field :scoring_value %>
          <%= f.error_message_on :scoring_value %>
        <% end %>
      </div>

    </div>
    <div class="right eight columns alpha" data-hook="admin_product_recommendation_form_right">

      <div data-hook="admin_product_recommendation_form_comment_title">
        <%= f.field_container :comment_title do %>
          <%= f.label :comment_title %>
          <%= f.text_field :comment_title, :class => 'fullwidth title', :required => true %>
          <%= f.error_message_on :comment_title %>
        <% end %>
      </div>

      <div data-hook="admin_product_recommendation_form_comment">
        <%= f.field_container :comment do %>
          <%= f.label :comment %>
          <%= f.text_area :comment, :class => 'fullwidth' %>
          <%= f.error_message_on :comment %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row omega" data-hook="admin_product_recommendation_form_submit">
    <% if product_recommendation.new_record? %>
      <%= button Spree.t('actions.create'), 'ok' %>
      <%#= render :partial => 'spree/admin/shared/new_resource_links' %>
    <% else %>
      <%= button Spree.t('actions.edit'), 'ok' %>
      <%#= render :partial => 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </div>



<% end %>

app/views/spree/admin/product_recommendations/_product_recommendations_table.html.erb
<% if product_recommendations.present? %>

<table class="index">
  <thead>
  <tr>
    <th><%= Spree::ProductRecommendation.human_attribute_name(:recommendation_source) %></th>
    <th><%= Spree::ProductRecommendation.human_attribute_name(:comment_title) %></th>
    <th><%= Spree::ProductRecommendation.human_attribute_name(:comment) %></th>
    <th><%= Spree::ProductRecommendation.human_attribute_name(:scoring_type) %></th>
    <th><%= Spree::ProductRecommendation.human_attribute_name(:scoring_value) %></th>
    <th><%= Spree.t('actions.edit') %></th>
  </tr>
  </thead>
  <tbody>
    <% product_recommendations.each do |recommendation| %>
      <tr id="<%= dom_id(recommendation, :sel)%>">
        <td><%= recommendation.recommendation_source %></td>
        <td><%= recommendation.comment_title %></td>
        <td><%= recommendation.comment %></td>
        <td><%= recommendation.display_scoring_type %></td>
        <td><%= recommendation.scoring_value %></td>
        <td>
          <%= link_to Spree.t('actions.edit'), edit_admin_product_product_recommendation_url(recommendation.product, recommendation) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <tr><td colspan="5"><%= t('.none') %></td></tr>
<% end %>

app/views/spree/admin/product_recommendations/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "ProductRecommendations"} %>


<h1><%= Spree.t('edit_product_recommendation') %></h1>
<%= render 'form', product: @product, product_recommendation: @product_recommendation %>

<% content_for :page_actions do %>
  <% #if can?(:create, Spree::ProductRecommendation) %>
  <li id="new_product_recommendation_link">
    <%= button_link_to Spree.t(:new_product_recommendation), new_admin_product_product_recommendation_url(@product), { :icon => 'plus', :id => 'new_product_recommendation_link' } %>
  </li>
  <% #end %>
<% end %>

app/views/spree/admin/product_recommendations/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "ProductRecommendations"} %>

<div id="product_recommendations">
	<h1><%= Spree.t('product_recommendations') %></h1>

  <%= render "product_recommendations_table", product_recommendations: @product_recommendations %>
</div>

<% content_for :page_actions do %>
  <% #if can?(:create, Spree::ProductRecommendation) %>
  <li id="new_product_recommendation_link">
    <%= button_link_to Spree.t(:new_product_recommendation), new_admin_product_product_recommendation_url(@product), { :icon => 'plus', :id => 'new_product_recommendation_link' } %>
  </li>
  <% #end %>
<% end %>

app/views/spree/admin/product_recommendations/new.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "ProductRecommendations"} %>

<h1><%= Spree.t('new_product_recommendation') %></h1>

<%= render 'form', product: @product, product_recommendation: @product_recommendation %>

app/views/spree/admin/shared/_product_recommendations_product_tabs.html.erb
<%= content_tag :li, :class => ('active' if current == 'ProductRecommendations') do %>
  <%= link_to_with_icon 'edit', Spree.t(:product_recommendations), spree.admin_product_product_recommendations_url(@product) %>
<% end if can?(:admin, Spree::ProductRecommendation) %>

app/views/spree/products/_product_recommendations.html.erb
<% if @product.product_recommendations.visible.any? %>

  <h6><%= Spree.t(:product_recommendations) %></h6>

  <ul id="product_recommendations" class="inline product-listing" data-hook>
    <% @product.product_recommendations.each do |product_recommendation| %>
      <li>
        <%= product_recommendation.recommendation_source %>
        <%= product_recommendation.display_scoring_type%>
        <%= product_recommendation.scoring_value %>
      </li>
    <% end %>
  </ul>
<% end %>